// Depth charts (2026 offseason). slot codes: QB, RB1, RB2, WR1, WR2, WR3, TE1 (offense)
// EDGE, DL, LB, CB, S (defense stars), K (special teams).
// Player-team mapping cross-checked against July 2026 consensus rankings.
export const DEPTH = {
  ARI: { QB: 'Jacoby Brissett', RB1: 'Jeremiyah Love', RB2: 'Trey Benson', WR1: 'Marvin Harrison Jr.', WR2: 'Michael Wilson', WR3: 'Greg Dortch', TE1: 'Trey McBride',
         EDGE: 'Josh Sweat', DL: 'Calais Campbell', LB: 'Akeem Davis-Gaither', CB: 'Garrett Williams', S: 'Budda Baker', K: 'Chad Ryland' },
  ATL: { QB: 'Tua Tagovailoa', RB1: 'Bijan Robinson', RB2: 'Tyler Allgeier', WR1: 'Drake London', WR2: 'Darnell Mooney', WR3: 'Ray-Ray McCloud III', TE1: 'Kyle Pitts',
         EDGE: 'Arnold Ebiketie', DL: 'David Onyemata', LB: 'Kaden Elliss', CB: 'A.J. Terrell', S: 'Jessie Bates III', K: 'Younghoe Koo' },
  BAL: { QB: 'Lamar Jackson', RB1: 'Derrick Henry', RB2: 'Justice Hill', WR1: 'Zay Flowers', WR2: 'Rashod Bateman', WR3: 'Devontez Walker', TE1: 'Isaiah Likely',
         EDGE: 'Trey Hendrickson', DL: 'Nnamdi Madubuike', LB: 'Roquan Smith', CB: 'Nate Wiggins', S: 'Kyle Hamilton', K: 'Tyler Loop' },
  BUF: { QB: 'Josh Allen', RB1: 'James Cook III', RB2: 'Ray Davis', WR1: 'DJ Moore', WR2: 'Khalil Shakir', WR3: 'Keon Coleman', TE1: 'Dalton Kincaid',
         EDGE: 'Greg Rousseau', DL: 'Ed Oliver', LB: 'Terrel Bernard', CB: 'Christian Benford', S: 'Cole Bishop', K: 'Tyler Bass' },
  CAR: { QB: 'Bryce Young', RB1: 'Chuba Hubbard', RB2: 'Trevor Etienne', WR1: 'Tetairoa McMillan', WR2: 'John Metchie III', WR3: 'Xavier Legette', TE1: 'Ja’Tavion Sanders',
         EDGE: 'D.J. Wonnum', DL: 'Derrick Brown', LB: 'Trevin Wallace', CB: 'Jaycee Horn', S: 'Trevon Moehrig', K: 'Eddy Pineiro' },
  CHI: { QB: 'Caleb Williams', RB1: 'D’Andre Swift', RB2: 'Kyle Monangai', WR1: 'Rome Odunze', WR2: 'Luther Burden III', WR3: 'Olamide Zaccheaus', TE1: 'Colston Loveland',
         EDGE: 'Montez Sweat', DL: 'Gervon Dexter Sr.', LB: 'Tremaine Edmunds', CB: 'Jaylon Johnson', S: 'Jaquan Brisker', K: 'Cairo Santos' },
  CIN: { QB: 'Joe Burrow', RB1: 'Chase Brown', RB2: 'Samaje Perine', WR1: 'Ja’Marr Chase', WR2: 'Tee Higgins', WR3: 'Andrei Iosivas', TE1: 'Mike Gesicki',
         EDGE: 'Shemar Stewart', DL: 'B.J. Hill', LB: 'Logan Wilson', CB: 'DJ Turner II', S: 'Jordan Battle', K: 'Evan McPherson' },
  CLE: { QB: 'Kirk Cousins', RB1: 'Quinshon Judkins', RB2: 'Jerome Ford', WR1: 'Jerry Jeudy', WR2: 'Cedric Tillman', WR3: 'Isaiah Bond', TE1: 'David Njoku',
         EDGE: 'Myles Garrett', DL: 'Mason Graham', LB: 'Carson Schwesinger', CB: 'Denzel Ward', S: 'Grant Delpit', K: 'Dustin Hopkins' },
  DAL: { QB: 'Dak Prescott', RB1: 'Javonte Williams', RB2: 'Jaydon Blue', WR1: 'CeeDee Lamb', WR2: 'George Pickens', WR3: 'Jalen Tolbert', TE1: 'Jake Ferguson',
         EDGE: 'Dante Fowler Jr.', DL: 'Kenny Clark', LB: 'DeMarvion Overshown', CB: 'DaRon Bland', S: 'Malik Hooker', K: 'Brandon Aubrey' },
  DEN: { QB: 'Bo Nix', RB1: 'RJ Harvey', RB2: 'J.K. Dobbins', WR1: 'Jaylen Waddle', WR2: 'Courtland Sutton', WR3: 'Marvin Mims Jr.', TE1: 'Evan Engram',
         EDGE: 'Nik Bonitto', DL: 'Zach Allen', LB: 'Dre Greenlaw', CB: 'Pat Surtain II', S: 'Talanoa Hufanga', K: 'Wil Lutz' },
  DET: { QB: 'Jared Goff', RB1: 'Jahmyr Gibbs', RB2: 'Craig Reynolds', WR1: 'Amon-Ra St. Brown', WR2: 'Jameson Williams', WR3: 'Tim Patrick', TE1: 'Sam LaPorta',
         EDGE: 'Aidan Hutchinson', DL: 'DJ Reader', LB: 'Jack Campbell', CB: 'Terrion Arnold', S: 'Brian Branch', K: 'Jake Bates' },
  GB:  { QB: 'Jordan Love', RB1: 'Josh Jacobs', RB2: 'MarShawn Lloyd', WR1: 'Christian Watson', WR2: 'Jayden Reed', WR3: 'Matthew Golden', TE1: 'Tucker Kraft',
         EDGE: 'Micah Parsons', DL: 'Devonte Wyatt', LB: 'Quay Walker', CB: 'Keisean Nixon', S: 'Xavier McKinney', K: 'Brandon McManus' },
  HOU: { QB: 'C.J. Stroud', RB1: 'David Montgomery', RB2: 'Woody Marks', WR1: 'Nico Collins', WR2: 'Christian Kirk', WR3: 'Jayden Higgins', TE1: 'Dalton Schultz',
         EDGE: 'Will Anderson Jr.', DL: 'Tim Settle', LB: 'Azeez Al-Shaair', CB: 'Derek Stingley Jr.', S: 'Calen Bullock', K: 'Ka’imi Fairbairn' },
  IND: { QB: 'Daniel Jones', RB1: 'Jonathan Taylor', RB2: 'DJ Giddens', WR1: 'Alec Pierce', WR2: 'Josh Downs', WR3: 'Adonai Mitchell', TE1: 'Tyler Warren',
         EDGE: 'Laiatu Latu', DL: 'DeForest Buckner', LB: 'Zaire Franklin', CB: 'Sauce Gardner', S: 'Camryn Bynum', K: 'Spencer Shrader' },
  JAX: { QB: 'Trevor Lawrence', RB1: 'Bhayshul Tuten', RB2: 'Tank Bigsby', WR1: 'Brian Thomas Jr.', WR2: 'Jakobi Meyers', WR3: 'Parker Washington', TE1: 'Brenton Strange',
         EDGE: 'Josh Hines-Allen', DL: 'Arik Armstead', LB: 'Devin Lloyd', CB: 'Travis Hunter', S: 'Eric Murray', K: 'Cam Little' },
  KC:  { QB: 'Patrick Mahomes', RB1: 'Kenneth Walker III', RB2: 'Isiah Pacheco', WR1: 'Rashee Rice', WR2: 'Xavier Worthy', WR3: 'Hollywood Brown', TE1: 'Noah Gray',
         EDGE: 'George Karlaftis', DL: 'Chris Jones', LB: 'Nick Bolton', CB: 'Trent McDuffie', S: 'Bryan Cook', K: 'Harrison Butker' },
  LV:  { QB: 'Fernando Mendoza', RB1: 'Ashton Jeanty', RB2: 'Raheem Mostert', WR1: 'Tre Tucker', WR2: 'Jalen Nailor', WR3: 'Dont’e Thornton Jr.', TE1: 'Brock Bowers',
         EDGE: 'Maxx Crosby', DL: 'Christian Wilkins', LB: 'Devin White', CB: 'Jakorian Bennett', S: 'Isaiah Pola-Mao', K: 'Daniel Carlson' },
  LAC: { QB: 'Justin Herbert', RB1: 'Omarion Hampton', RB2: 'Najee Harris', WR1: 'Ladd McConkey', WR2: 'Quentin Johnston', WR3: 'Tre Harris', TE1: 'Oronde Gadsden II',
         EDGE: 'Tuli Tuipulotu', DL: 'Teair Tart', LB: 'Daiyan Henley', CB: 'Tarheeb Still', S: 'Derwin James Jr.', K: 'Cameron Dicker' },
  LAR: { QB: 'Matthew Stafford', RB1: 'Kyren Williams', RB2: 'Blake Corum', WR1: 'Puka Nacua', WR2: 'Davante Adams', WR3: 'Jordan Whittington', TE1: 'Terrance Ferguson',
         EDGE: 'Jared Verse', DL: 'Braden Fiske', LB: 'Omar Speights', CB: 'Cobie Durant', S: 'Quentin Lake', K: 'Joshua Karty' },
  MIA: { QB: 'Malik Willis', RB1: 'De’Von Achane', RB2: 'Ollie Gordon II', WR1: 'Malik Washington', WR2: 'Nick Westbrook-Ikhine', WR3: 'Tahj Washington', TE1: 'Julian Hill',
         EDGE: 'Bradley Chubb', DL: 'Zach Sieler', LB: 'Jordyn Brooks', CB: 'Storm Duck', S: 'Minkah Fitzpatrick', K: 'Jason Sanders' },
  MIN: { QB: 'J.J. McCarthy', RB1: 'Aaron Jones Sr.', RB2: 'Jordan Mason', WR1: 'Justin Jefferson', WR2: 'Jordan Addison', WR3: 'Tai Felton', TE1: 'T.J. Hockenson',
         EDGE: 'Jonathan Greenard', DL: 'Javon Hargrave', LB: 'Ivan Pace Jr.', CB: 'Byron Murphy Jr.', S: 'Theo Jackson', K: 'Will Reichard' },
  NE:  { QB: 'Drake Maye', RB1: 'TreVeyon Henderson', RB2: 'Rhamondre Stevenson', WR1: 'A.J. Brown', WR2: 'Romeo Doubs', WR3: 'DeMario Douglas', TE1: 'Hunter Henry',
         EDGE: 'Harold Landry III', DL: 'Milton Williams', LB: 'Robert Spillane', CB: 'Christian Gonzalez', S: 'Kyle Dugger', K: 'Andy Borregales' },
  NO:  { QB: 'Tyler Shough', RB1: 'Travis Etienne Jr.', RB2: 'Kendre Miller', WR1: 'Chris Olave', WR2: 'Jordyn Tyson', WR3: 'Rashid Shaheed', TE1: 'Juwan Johnson',
         EDGE: 'Carl Granderson', DL: 'Bryan Bresee', LB: 'Demario Davis', CB: 'Kool-Aid McKinstry', S: 'Justin Reid', K: 'Blake Grupe' },
  NYG: { QB: 'Jaxson Dart', RB1: 'Cam Skattebo', RB2: 'Tyrone Tracy Jr.', WR1: 'Malik Nabers', WR2: 'Darius Slayton', WR3: 'Jalin Hyatt', TE1: 'Theo Johnson',
         EDGE: 'Brian Burns', DL: 'Dexter Lawrence', LB: 'Bobby Okereke', CB: 'Paulson Adebo', S: 'Tyler Nubin', K: 'Graham Gano' },
  NYJ: { QB: 'Justin Fields', RB1: 'Breece Hall', RB2: 'Braelon Allen', WR1: 'Garrett Wilson', WR2: 'Josh Reynolds', WR3: 'Xavier Gipson', TE1: 'Mason Taylor',
         EDGE: 'David Bailey', DL: 'Quinnen Williams', LB: 'Quincy Williams', CB: 'Brandon Stephens', S: 'Andre Cisco', K: 'Anders Carlson' },
  PHI: { QB: 'Jalen Hurts', RB1: 'Saquon Barkley', RB2: 'Will Shipley', WR1: 'DeVonta Smith', WR2: 'Makai Lemon', WR3: 'Jahan Dotson', TE1: 'Dallas Goedert',
         EDGE: 'Nolan Smith Jr.', DL: 'Jalen Carter', LB: 'Zack Baun', CB: 'Quinyon Mitchell', S: 'Reed Blankenship', K: 'Jake Elliott' },
  PIT: { QB: 'Aaron Rodgers', RB1: 'Jaylen Warren', RB2: 'Rico Dowdle', WR1: 'DK Metcalf', WR2: 'Michael Pittman Jr.', WR3: 'Calvin Austin III', TE1: 'Pat Freiermuth',
         EDGE: 'T.J. Watt', DL: 'Keeanu Benton', LB: 'Patrick Queen', CB: 'Joey Porter Jr.', S: 'DeShon Elliott', K: 'Chris Boswell' },
  SF:  { QB: 'Brock Purdy', RB1: 'Christian McCaffrey', RB2: 'Isaac Guerendo', WR1: 'Mike Evans', WR2: 'Ricky Pearsall', WR3: 'Jauan Jennings', TE1: 'George Kittle',
         EDGE: 'Nick Bosa', DL: 'Mykel Williams', LB: 'Fred Warner', CB: 'Deommodore Lenoir', S: 'Malik Mustapha', K: 'Jake Moody' },
  SEA: { QB: 'Sam Darnold', RB1: 'Zach Charbonnet', RB2: 'Jadarian Price', WR1: 'Jaxon Smith-Njigba', WR2: 'Cooper Kupp', WR3: 'Tory Horton', TE1: 'AJ Barner',
         EDGE: 'Derick Hall', DL: 'Leonard Williams', LB: 'Ernest Jones IV', CB: 'Devon Witherspoon', S: 'Julian Love', K: 'Jason Myers' },
  TB:  { QB: 'Baker Mayfield', RB1: 'Bucky Irving', RB2: 'Rachaad White', WR1: 'Emeka Egbuka', WR2: 'Chris Godwin Jr.', WR3: 'Jalen McMillan', TE1: 'Cade Otton',
         EDGE: 'Yaya Diaby', DL: 'Vita Vea', LB: 'SirVocea Dennis', CB: 'Zyon McCollum', S: 'Antoine Winfield Jr.', K: 'Chase McLaughlin' },
  TEN: { QB: 'Cam Ward', RB1: 'Tony Pollard', RB2: 'Tyjae Spears', WR1: 'Carnell Tate', WR2: 'Wan’Dale Robinson', WR3: 'Elic Ayomanor', TE1: 'Chig Okonkwo',
         EDGE: 'Arden Key', DL: 'Jeffery Simmons', LB: 'Cody Barton', CB: 'L’Jarius Sneed', S: 'Amani Hooker', K: 'Joey Slye' },
  WAS: { QB: 'Jayden Daniels', RB1: 'Jacory Croskey-Merritt', RB2: 'Austin Ekeler', WR1: 'Terry McLaurin', WR2: 'Deebo Samuel', WR3: 'Noah Brown', TE1: 'Zach Ertz',
         EDGE: 'Dorance Armstrong', DL: 'Daron Payne', LB: 'Frankie Luvu', CB: 'Marshon Lattimore', S: 'Quan Martin', K: 'Matt Gay' }
};

// July 2026 consensus PPR top 100 (seed for the default ranking set).
export const DEFAULT_BOARD = [
  ['Jahmyr Gibbs','RB','DET'],['Bijan Robinson','RB','ATL'],['Puka Nacua','WR','LAR'],['Ja’Marr Chase','WR','CIN'],
  ['Christian McCaffrey','RB','SF'],['Jaxon Smith-Njigba','WR','SEA'],['Amon-Ra St. Brown','WR','DET'],['Jonathan Taylor','RB','IND'],
  ['De’Von Achane','RB','MIA'],['Drake London','WR','ATL'],['Rashee Rice','WR','KC'],['CeeDee Lamb','WR','DAL'],
  ['Chase Brown','RB','CIN'],['Justin Jefferson','WR','MIN'],['Ashton Jeanty','RB','LV'],['Derrick Henry','RB','BAL'],
  ['James Cook III','RB','BUF'],['A.J. Brown','WR','NE'],['Chris Olave','WR','NO'],['Saquon Barkley','RB','PHI'],
  ['George Pickens','WR','DAL'],['Omarion Hampton','RB','LAC'],['Nico Collins','WR','HOU'],['Josh Jacobs','RB','GB'],
  ['Jeremiyah Love','RB','ARI'],['Zay Flowers','WR','BAL'],['Garrett Wilson','WR','NYJ'],['Breece Hall','RB','NYJ'],
  ['Kenneth Walker III','RB','KC'],['DeVonta Smith','WR','PHI'],['Cam Skattebo','RB','NYG'],['Josh Allen','QB','BUF'],
  ['Kyren Williams','RB','LAR'],['Tetairoa McMillan','WR','CAR'],['Emeka Egbuka','WR','TB'],['Travis Etienne Jr.','RB','NO'],
  ['Malik Nabers','WR','NYG'],['Javonte Williams','RB','DAL'],['Tee Higgins','WR','CIN'],['Davante Adams','WR','LAR'],
  ['Trey McBride','TE','ARI'],['Terry McLaurin','WR','WAS'],['Bucky Irving','RB','TB'],['Jameson Williams','WR','DET'],
  ['Ladd McConkey','WR','LAC'],['D’Andre Swift','RB','CHI'],['Rome Odunze','WR','CHI'],['Jaylen Waddle','WR','DEN'],
  ['DJ Moore','WR','BUF'],['Alec Pierce','WR','IND'],['Luther Burden III','WR','CHI'],['Brock Bowers','TE','LV'],
  ['Courtland Sutton','WR','DEN'],['Quinshon Judkins','RB','CLE'],['Bhayshul Tuten','RB','JAX'],['Marvin Harrison Jr.','WR','ARI'],
  ['Mike Evans','WR','SF'],['DK Metcalf','WR','PIT'],['Drake Maye','QB','NE'],['TreVeyon Henderson','RB','NE'],
  ['Wan’Dale Robinson','WR','TEN'],['Michael Pittman Jr.','WR','PIT'],['Christian Watson','WR','GB'],['Jakobi Meyers','WR','JAX'],
  ['Lamar Jackson','QB','BAL'],['Tony Pollard','RB','TEN'],['Carnell Tate','WR','TEN'],['Parker Washington','WR','JAX'],
  ['Jaylen Warren','RB','PIT'],['David Montgomery','RB','HOU'],['Jadarian Price','RB','SEA'],['Joe Burrow','QB','CIN'],
  ['Rhamondre Stevenson','RB','NE'],['Chuba Hubbard','RB','CAR'],['Rico Dowdle','RB','PIT'],['Jordyn Tyson','WR','NO'],
  ['Brian Thomas Jr.','WR','JAX'],['Chris Godwin Jr.','WR','TB'],['Jayden Reed','WR','GB'],['Dak Prescott','QB','DAL'],
  ['Jayden Daniels','QB','WAS'],['Michael Wilson','WR','ARI'],['Josh Downs','WR','IND'],['Colston Loveland','TE','CHI'],
  ['Quentin Johnston','WR','LAC'],['Jalen Hurts','QB','PHI'],['Khalil Shakir','WR','BUF'],['Brock Purdy','QB','SF'],
  ['RJ Harvey','RB','DEN'],['Jordan Addison','WR','MIN'],['Tyler Warren','TE','IND'],['Matthew Stafford','QB','LAR'],
  ['Xavier Worthy','WR','KC'],['Aaron Jones Sr.','RB','MIN'],['Ricky Pearsall','WR','SF'],['Makai Lemon','WR','PHI'],
  ['Romeo Doubs','WR','NE'],['Trevor Lawrence','QB','JAX'],['John Metchie III','WR','CAR'],['Sam LaPorta','TE','DET']
];
