// 32 NFL teams — 2026 season. Coaching staffs reflect the 2026 hiring cycle
// (10 new head coaches). Schemes/analyses are editorial seed content.
export const TEAMS = [
  {
    abbr: 'ARI', name: 'Arizona Cardinals', conference: 'NFC', division: 'West',
    head_coach: 'Mike LaFleur', oc_name: 'Mike LaFleur (play-caller)', dc_name: 'TBD (camp)',
    off_scheme: 'Shanahan-tree wide zone',
    off_scheme_detail: 'LaFleur brings the Rams outside-zone/play-action system. Heavy 11 personnel with condensed splits and pre-snap motion. Rookie RB Jeremiyah Love (No. 3 overall) is the engine; Jacoby Brissett is a point-guard QB who keeps the offense on schedule, which funnels targets to Trey McBride and Marvin Harrison Jr. on play-action in-breakers.',
    def_scheme: '3-4 hybrid, split-safety shells',
    def_scheme_detail: 'Carryover personnel from the Gannon era: two-high shells, simulated pressures, light boxes that dare you to run.',
    st_coordinator: null,
    ol_analysis: 'Middle-of-the-pack unit that fits the zone scheme better than it drives people off the ball. Paris Johnson Jr. is a real LT anchor. Zone blocking widens lanes for Love’s one-cut style — good news for his rookie-year efficiency.',
    dl_analysis: 'Josh Sweat headlines an ascending front. Scheme asks the line to two-gap less and shoot gaps more on passing downs.',
    lb_analysis: 'Fast, undersized group built to run to the flats in the split-zone era. Fantasy-relevant only in IDP.',
    secondary_analysis: 'Budda Baker still sets the tone. Two-high structure suppresses deep shots, so opposing WR1s see volume underneath rather than chunk plays.',
    st_analysis: 'Stable operation. Return game gets a jolt if Love sees kick-return work early (unlikely once he owns the backfield).',
    coach_analysis: 'First-time HC from the McVay/Shanahan tree. Expect a run-first identity that protects Brissett and force-feeds Love and McBride. McBride is a top-2 TE in this system; MHJ’s ceiling depends on play-action volume, not raw target share.',
    primary_color: '#97233F', secondary_color: '#FFB612'
  },
  {
    abbr: 'ATL', name: 'Atlanta Falcons', conference: 'NFC', division: 'South',
    head_coach: 'Kevin Stefanski', oc_name: 'Kevin Stefanski (play-caller)', dc_name: 'Jeff Ulbrich',
    off_scheme: 'Wide zone + heavy play-action',
    off_scheme_detail: 'Stefanski’s outside-zone system with condensed formations and multi-TE looks. QB battle between Tua Tagovailoa (one-year deal) and Michael Penix Jr. (returning from knee injury) defines the passing game: Tua = rhythm/RPO quick game, Penix = vertical play-action.',
    def_scheme: '4-2-5 zone-match',
    def_scheme_detail: 'Ulbrich carryover: four-down fronts, zone-match coverage, pressure via overload fronts rather than exotic blitzes.',
    st_coordinator: null,
    ol_analysis: 'Top-10 unit anchored by Chris Lindstrom, arguably the best RG in football. Elite zone-blocking fits Bijan Robinson perfectly — this line is a big part of his top-3 pick case.',
    dl_analysis: 'Still searching for a true edge alpha. Interior is stout; pass rush lives on scheme.',
    lb_analysis: 'Kaden Elliss is a blitz weapon. Athletic but thin group.',
    secondary_analysis: 'Jessie Bates III is a top-3 ballhawk safety and A.J. Terrell travels with WR1s. Tough matchup for opposing passing games.',
    st_analysis: 'Solid across the board; no fantasy needle-movers.',
    coach_analysis: 'Stefanski won Coach of the Year twice in Cleveland with less talent. Bijan in a Stefanski wide-zone attack is a 350-touch nightmare (in the good way). Drake London wins on play-action digs regardless of who starts at QB — but Penix winning the job would raise his ceiling and lower his floor.',
    primary_color: '#A71930', secondary_color: '#000000'
  },
  {
    abbr: 'BAL', name: 'Baltimore Ravens', conference: 'AFC', division: 'North',
    head_coach: 'Jesse Minter', oc_name: 'TBD (camp)', dc_name: 'Minter influence (defense-first HC)',
    off_scheme: 'Pistol/gun spread-option core',
    off_scheme_detail: 'The Lamar Jackson offense survives the coaching change: pistol formations, RPOs, designed QB run game, downhill gap runs for Derrick Henry. New staff keeps the skeleton — you don’t hire away from this engine.',
    def_scheme: 'Multiple 3-4, heavy disguise (Minter system)',
    def_scheme_detail: 'Minter brings the Chargers/Michigan pressure-disguise system: late-rotating safeties, creeper pressures, man-match behind it. Trey Hendrickson (4yr/$112M) gives it a real edge closer.',
    st_coordinator: null,
    ol_analysis: 'Retooled after losing Tyler Linderbaum to a record Raiders deal — the new interior is the offense’s biggest question. Henry’s gap runs depend on double-teams at the point; watch camp battles at center closely before drafting Henry at cost.',
    dl_analysis: 'Hendrickson + Nnamdi Madubuike is a legit inside-out rush. Top-5 front on paper.',
    lb_analysis: 'Roquan Smith remains the green-dot tone-setter. Elite run-and-chase group.',
    secondary_analysis: 'Kyle Hamilton is the most versatile defender in football and Minter will weaponize him everywhere: slot, box, post, edge.',
    st_analysis: 'Post-Tucker era: Tyler Loop handles kicks. Slight downgrade from automatic.',
    coach_analysis: 'First-time HC, defensive specialist. The bet: defense wins the division while Lamar’s offense runs itself. Fantasy read — slight pass-volume risk if the defense forces more short fields and run-out-the-clock scripts. Lamar stays a top-3 QB; Zay Flowers target share is safe; Henry TD-dependent but the profile holds.',
    primary_color: '#241773', secondary_color: '#9E7C0C'
  },
  {
    abbr: 'BUF', name: 'Buffalo Bills', conference: 'AFC', division: 'East',
    head_coach: 'Joe Brady', oc_name: 'Joe Brady (play-caller)', dc_name: 'TBD (camp)',
    off_scheme: 'Spread, QB-centric, empty-heavy',
    off_scheme_detail: 'Brady promoted after McDermott’s surprise firing. Continuity for Josh Allen: spread sets, option routes for Khalil Shakir, James Cook as the metronome, and the league’s best scramble-drill offense. New wrinkle: DJ Moore arrives as the true X they’ve lacked.',
    def_scheme: '4-2-5, zone-heavy (post-McDermott reset)',
    def_scheme_detail: 'New DC inherits a sound but aging shell. Expect simplified two-high with Christian Benford in match coverage.',
    st_coordinator: null,
    ol_analysis: 'Sneaky-good, cohesive five led by Dion Dawkins. Elite in gap-scheme short yardage — part of why Allen vultures every goal-line score. That cost is priced into Cook.',
    dl_analysis: 'Greg Rousseau leads a rotation that’s deep but lacks a 15-sack alpha.',
    lb_analysis: 'Terrel Bernard is a tackle machine when healthy.',
    secondary_analysis: 'Benford is a top-10 corner. Safety room in transition after years of Hyde/Poyer stability.',
    st_analysis: 'Tyler Bass fully rebounded; strong coverage units.',
    coach_analysis: 'Brady calls a QB-friendly, pace-up offense. DJ Moore + Shakir + Kincaid gives Allen his deepest target tree ever — which slightly caps any single receiver but keeps Allen the fantasy QB1 overall. Cook is a locked-in RB1; Moore is a value if his ADP lags the situation upgrade.',
    primary_color: '#00338D', secondary_color: '#C60C30'
  },
  {
    abbr: 'CAR', name: 'Carolina Panthers', conference: 'NFC', division: 'South',
    head_coach: 'Dave Canales', oc_name: 'Brad Idzik', dc_name: 'Ejiro Evero',
    off_scheme: 'West Coast timing + boot game',
    off_scheme_detail: 'Canales’ system: quick timing throws, bootlegs, and a physical duo-run game. Tetairoa McMillan is the clear alpha; Bryce Young’s year-three leap with Canales continues to be the story.',
    def_scheme: '3-4 two-high (Evero)',
    def_scheme_detail: 'Evero runs a Fangio-style shell: light boxes, quarters rotation, rush four and rally.',
    st_coordinator: null,
    ol_analysis: 'Quietly rebuilt into a respectable unit — Ickey Ekwonu has settled at LT. Duo-heavy run game gives Chuba Hubbard a stable floor.',
    dl_analysis: 'Derrick Brown is a double-team eraser. Edge rush is the roster’s biggest hole.',
    lb_analysis: 'Rebuilding level of the defense; targeted heavily by opposing play-action.',
    secondary_analysis: 'Jaycee Horn is elite when healthy; Trevon Moehrig added real physicality at safety.',
    st_analysis: 'League-average across the board.',
    coach_analysis: 'Canales has revived every QB he’s touched. McMillan commands a 25%+ target share as the only proven separator; Hubbard is a volume-based RB2 until the rookie class pushes. Young is a streaming QB with a rushing floor that’s quietly improved.',
    primary_color: '#0085CA', secondary_color: '#101820'
  },
  {
    abbr: 'CHI', name: 'Chicago Bears', conference: 'NFC', division: 'North',
    head_coach: 'Ben Johnson', oc_name: 'Declan Doyle', dc_name: 'Dennis Allen',
    off_scheme: 'Motion-heavy multiple (Johnson system)',
    off_scheme_detail: 'Year two of Ben Johnson’s offense: heaviest pre-snap motion rate in football, condensed sets into deep crossers, screens as extended runs. Caleb Williams’ sophomore-system leap is the NFC North’s swing factor. Rome Odunze and Luther Burden III both profile as 1,000-yard threats; Colston Loveland is the Sam LaPorta role.',
    def_scheme: '4-3 zone pressure (Dennis Allen)',
    def_scheme_detail: 'Allen dials simulated pressures with Montez Sweat as the fixed rush point.',
    st_coordinator: null,
    ol_analysis: 'Massively upgraded interior (Thuney/Jackson-era moves) — now a top-10 unit that travels. Everything about this offense starts with the A-gap double team; D’Andre Swift’s efficiency spike is real.',
    dl_analysis: 'Sweat plus a deep interior rotation. Good, not elite.',
    lb_analysis: 'Tremaine Edmunds erases the middle of the field in zone.',
    secondary_analysis: 'Jaylon Johnson is a shutdown boundary corner; the slot is targetable.',
    st_analysis: 'Cairo Santos steady; return game upgraded with Burden’s wiggle.',
    coach_analysis: 'Johnson turned Detroit into a top-3 offense; year two in Chicago is when the compounding kicks in. Caleb is a top-8 fantasy QB bet, Loveland the breakout TE pick, and the Odunze/Burden duo will both eat — Johnson’s system historically supports two top-24 WRs.',
    primary_color: '#0B162A', secondary_color: '#C83803'
  },
  {
    abbr: 'CIN', name: 'Cincinnati Bengals', conference: 'AFC', division: 'North',
    head_coach: 'Zac Taylor', oc_name: 'Dan Pitcher', dc_name: 'Al Golden',
    off_scheme: '11-personnel spread, five-out dropback',
    off_scheme_detail: 'The Burrow offense: spread the field, live in empty, isolate Ja’Marr Chase on the boundary. Chase Brown handles a three-down role. Volume is never the question here — pass protection is.',
    def_scheme: '4-3 over, zone-match',
    def_scheme_detail: 'Post-Hendrickson (walked to Baltimore): the rush now leans on 2025 first-rounder Shemar Stewart’s development. Defense again projects bottom-half, which keeps Cincy games in shootout scripts.',
    st_coordinator: null,
    ol_analysis: 'Perennially the offense’s weak link, again retooled on the right side. Burrow’s quick-game mastery papers over it; deep shots to Chase are where the pressure shows up.',
    dl_analysis: 'Losing Hendrickson’s 15+ sacks is enormous. Stewart’s tools are elite; production TBD.',
    lb_analysis: 'Logan Wilson is a reliable green dog and tackle accumulator.',
    secondary_analysis: 'Young corners in a scheme that asks a lot. Opposing WR2s smash here.',
    st_analysis: 'Evan McPherson stays one of the highest-upside fantasy kickers (volume + leg).',
    coach_analysis: 'Bad defense + elite QB = the best fantasy game environment in football. Chase is the WR1 overall case, Tee Higgins a top-15 WR, Chase Brown a top-12 RB on receiving volume alone, and Burrow a top-4 QB. Draft Bengals; thank the defense.',
    primary_color: '#FB4F14', secondary_color: '#000000'
  },
  {
    abbr: 'CLE', name: 'Cleveland Browns', conference: 'AFC', division: 'North',
    head_coach: 'Todd Monken', oc_name: 'Todd Monken (play-caller)', dc_name: 'TBD (camp)',
    off_scheme: 'Dropback spread, tempo (Monken system)',
    off_scheme_detail: 'Monken finally gets his own team and installs the pass-first spread he ran in Baltimore/Georgia. Kirk Cousins arrives as the veteran bridge with Quinshon Judkins as the bell-cow. Jerry Jeudy is the route-tree WR1; David Njoku feasts in Monken’s TE-friendly middle-of-field concepts.',
    def_scheme: '4-3 penetrate (Garrett-centric)',
    def_scheme_detail: 'Everything keys off Myles Garrett — wide-9 alignments, games and stunts inside off his gravity.',
    st_coordinator: null,
    ol_analysis: 'Better than its reputation when healthy — the tackles are the concern, and Cousins’ statue tendencies stress them. Judkins’ downhill style fits the gap-lean run game well.',
    dl_analysis: 'Garrett is still the best defensive player alive. Interior rebuilt around him.',
    lb_analysis: 'Carson Schwesinger broke out as a rookie; sideline-to-sideline range.',
    secondary_analysis: 'Denzel Ward remains a true CB1 shadow. Safety depth is thin.',
    st_analysis: 'Average unit; dome-free AFC North weather suppresses kicker value.',
    coach_analysis: 'Monken’s offenses throw to score, not to catch up. Cousins is a bridge, but he’s a rhythm-passer fit for this system — Njoku and Jeudy are the sneaky beneficiaries. Judkins projects 270+ touches. Temper it all with AFC North defenses twice each.',
    primary_color: '#311D00', secondary_color: '#FF3C00'
  },
  {
    abbr: 'DAL', name: 'Dallas Cowboys', conference: 'NFC', division: 'East',
    head_coach: 'Brian Schottenheimer', oc_name: 'Klayton Adams', dc_name: 'Matt Eberflus',
    off_scheme: 'West Coast base with vertical shots',
    off_scheme_detail: 'Dak Prescott with CeeDee Lamb and George Pickens — the best one-two receiver punch in the NFC East. Javonte Williams revived his career here in 2025 and returns as the lead back.',
    def_scheme: '4-3 zone (Eberflus)',
    def_scheme_detail: 'Post-Parsons trade, the rush is by committee. Eberflus plays conservative zone shells that concede completions and rally to tackle.',
    st_coordinator: null,
    ol_analysis: 'The dynasty-era dominance is gone but Tyler Smith is a top-5 guard and the unit is still above average. Fine pocket for Dak; road grading is just okay.',
    dl_analysis: 'Kenny Clark anchors; no Parsons-level closer. Pressure rate projects mid-pack.',
    lb_analysis: 'Eberflus turns LBs into tackle machines — IDP gold, real-life fine.',
    secondary_analysis: 'DaRon Bland and Trevon Diggs gamble for picks; boom-bust coverage unit.',
    st_analysis: 'Brandon Aubrey is the best fantasy kicker in football, full stop. 60-yarders are routine.',
    coach_analysis: 'The offense runs through Lamb (elite slot usage) and Pickens (boundary shots). Both are locked-in top-20 WRs. Javonte is a volume RB2. Dak remains a high-floor QB1 when the pass rate spikes in shootouts — which Eberflus’ defense guarantees.',
    primary_color: '#003594', secondary_color: '#869397'
  },
  {
    abbr: 'DEN', name: 'Denver Broncos', conference: 'AFC', division: 'West',
    head_coach: 'Sean Payton', oc_name: 'Joe Lombardi', dc_name: 'Vance Joseph',
    off_scheme: 'Payton West Coast, condensed + option routes',
    off_scheme_detail: 'Bo Nix year three in Payton’s system. Jaylen Waddle arrives from Miami as the joker/YAC weapon Payton has craved since Kamara-era — expect manufactured touches. Courtland Sutton stays the boundary possession X; RJ Harvey is the Kamara-role satellite back.',
    def_scheme: '3-4 pressure-heavy (Joseph)',
    def_scheme_detail: 'Top-3 defense in football. Pat Surtain II erases half the field; Vance Joseph blitzes at a top-5 rate with Nik Bonitto winning off the edge.',
    st_coordinator: null,
    ol_analysis: 'Quinn Meinerz mauls people; a top-8 unit that keeps Nix upright and clean. Zone/gap-mixed run game supports Harvey’s inside-out skill set.',
    dl_analysis: 'Zach Allen is a top-5 interior rusher nobody talks about. Deep, violent rotation.',
    lb_analysis: 'Fast flow-and-fill group behind a two-gapping front.',
    secondary_analysis: 'Surtain + Hufanga + Riley Moss: the league’s best coverage unit. Fade opposing WR1s.',
    st_analysis: 'Wil Lutz is a reliable dome-away kicker; Marvin Mims is a return-game TD threat.',
    coach_analysis: 'Payton offenses distribute — nobody dominates targets, everybody eats situationally. Waddle’s YAC role is the exception worth buying: Payton force-feeds his joker. Nix is a sneaky QB1 on rushing + schemed layups. Denver DEF is a top-2 fantasy defense pick.',
    primary_color: '#FB4F14', secondary_color: '#002244'
  },
  {
    abbr: 'DET', name: 'Detroit Lions', conference: 'NFC', division: 'North',
    head_coach: 'Dan Campbell', oc_name: 'John Morton', dc_name: 'Kelvin Sheppard',
    off_scheme: 'Wide zone + duo hybrid, motion-heavy',
    off_scheme_detail: 'The Ben Johnson bones survived: motion, unbalanced sets, and the league’s best RB screen game. Jahmyr Gibbs is the consensus 1.01 — the offense now explicitly runs through him after Montgomery’s exit. Amon-Ra owns the slot; Jameson Williams takes the lid off.',
    def_scheme: '4-3 attack front (Sheppard)',
    def_scheme_detail: 'Aidan Hutchinson healthy again headlines an aggressive, blitz-willing front. Brian Branch is the do-everything chess piece.',
    st_coordinator: null,
    ol_analysis: 'Still a top-3 line even through turnover — Penei Sewell is the best tackle in football. Goal-line pushes and screen walls are elite; this line is a big chunk of why Gibbs is the 1.01.',
    dl_analysis: 'Hutchinson’s return to form is the story; DJ Reader anchors inside.',
    lb_analysis: 'Jack Campbell developed into an every-down thumper.',
    secondary_analysis: 'Branch is a top-3 slot defender; boundary corners are targetable, keeping Lions games fast.',
    st_analysis: 'Jake Bates has a cannon — top-5 fantasy kicker in a top offense.',
    coach_analysis: 'Campbell’s aggression (4th-down rate, tempo) inflates possessions and red-zone trips. Gibbs 1.01, St. Brown top-5 WR, Jamo a weekly ceiling play, LaPorta a buy-back candidate. The only fantasy worry is blowout-driven fourth quarters.',
    primary_color: '#0076B6', secondary_color: '#B0B7BC'
  },
  {
    abbr: 'GB', name: 'Green Bay Packers', conference: 'NFC', division: 'North',
    head_coach: 'Matt LaFleur', oc_name: 'Adam Stenavich', dc_name: 'Jeff Hafley’s successor (TBD)',
    off_scheme: 'Wide zone, bunch formations, play-action',
    off_scheme_detail: 'LaFleur’s matchup-driven passing tree with Jordan Love. Josh Jacobs is the offense’s identity; the WR room (Watson, Reed, Golden) is deep but role-fluid — classic Packers ambiguity. Tucker Kraft is a top-8 TE in this play-action scheme.',
    def_scheme: '4-3 quarters (post-Hafley transition)',
    def_scheme_detail: 'Micah Parsons (2025 trade) is the entire pressure plan and it works: wide-9 rush, quarters shell behind.',
    st_coordinator: null,
    ol_analysis: 'Zach Tom is a top-10 tackle; the unit is built for zone-flow and screens. Jacobs’ patient one-cut style fits perfectly — his TD total is line-driven and sustainable.',
    dl_analysis: 'Parsons changes everything: double-teams, chips, sped-up throws. Best rush in the NFC North.',
    lb_analysis: 'Quay Walker athletic, occasionally out of position. Fine.',
    secondary_analysis: 'Xavier McKinney is an All-Pro ballhawk; corner depth thins fast after the top two.',
    st_analysis: 'McManus reliable; return game average.',
    coach_analysis: 'The annual Packers fantasy dilemma: great offense, no target hierarchy. Jacobs (300 touches) and Kraft are the safe buys; Love a mid-QB1. Among WRs, Reed’s slot role is the steadiest — but expect maddening week-to-week rotation again.',
    primary_color: '#203731', secondary_color: '#FFB612'
  },
  {
    abbr: 'HOU', name: 'Houston Texans', conference: 'AFC', division: 'South',
    head_coach: 'DeMeco Ryans', oc_name: 'Nick Caley', dc_name: 'Matt Burke',
    off_scheme: 'Shanahan-tree with vertical emphasis',
    off_scheme_detail: 'C.J. Stroud’s bounce-back is the AFC South’s biggest variable. David Montgomery imported from Detroit stabilizes a broken run game; Nico Collins remains a top-5 WR when upright. Rebuilt OL is the whole story.',
    def_scheme: '4-3 wide-9 (Ryans DNA)',
    def_scheme_detail: 'Will Anderson Jr. and Danielle Hunter form a top-3 edge duo. Stingley shadows. This defense is legitimately elite.',
    st_coordinator: null,
    ol_analysis: 'Gutted and rebuilt twice in two years — still bottom-10 until proven otherwise. It capped Stroud’s 2025 and it’s the primary risk on every Texans fantasy asset. Montgomery’s between-the-tackles style at least gives the line easy math.',
    dl_analysis: 'Anderson + Hunter + a deep interior: top-3 pressure rate incoming.',
    lb_analysis: 'Azeez Al-Shaair sets a violent tone; strong run fits.',
    secondary_analysis: 'Derek Stingley Jr. is a top-2 corner. Takeaway machine as a unit.',
    st_analysis: 'Ka’imi Fairbairn is a top-8 kicker when the offense functions.',
    coach_analysis: 'Elite defense + question-mark OL = moderate pace, run-lean scripts. Collins is matchup-proof; Stroud is a buy-low QB1 if the line stabilizes; Montgomery is a TD-dependent RB2 with a locked role. Houston DEF drafts top-5.',
    primary_color: '#03202F', secondary_color: '#A71930'
  },
  {
    abbr: 'IND', name: 'Indianapolis Colts', conference: 'AFC', division: 'South',
    head_coach: 'Shane Steichen', oc_name: 'Jim Bob Cooter', dc_name: 'Lou Anarumo',
    off_scheme: 'RPO-heavy spread with gap run game',
    off_scheme_detail: 'Daniel Jones stabilized the job in 2025 and re-signed. Jonathan Taylor remains the engine — Steichen’s RPO math keeps boxes light. Alec Pierce got paid (historic deal) as the field-stretcher; Tyler Warren is the do-it-all TE Steichen has schemed for; Josh Downs owns the slot. Sauce Gardner (2025 trade) transformed the defense.',
    def_scheme: 'Multiple/amoeba (Anarumo)',
    def_scheme_detail: 'Anarumo’s shape-shifting shells plus Sauce Gardner in shadow coverage — a top-10 unit.',
    st_coordinator: null,
    ol_analysis: 'Quenton Nelson still mauls; the unit is top-10 in gap/power. Taylor’s efficiency profile is directly tied to this line — and it’s healthy.',
    dl_analysis: 'DeForest Buckner’s heir apparent rotation; Laiatu Latu’s rush plan matured.',
    lb_analysis: 'Zaire Franklin: 150+ tackles, every year, like clockwork.',
    secondary_analysis: 'Sauce changes the math — opposing WR1s get erased, funneling targets to slots and TEs.',
    st_analysis: 'Average; Pierce occasionally moonlights on returns (don’t count on it).',
    coach_analysis: 'Steichen’s system produces a top-8 RB (Taylor, locked), a valuable slot (Downs, PPR floor), and a rookie-contract TE ceiling (Warren, top-6 TE bet). Jones is a streamer, not a season-long answer — which keeps this a run-first, Taylor-fed operation.',
    primary_color: '#002C5F', secondary_color: '#A2AAAD'
  },
  {
    abbr: 'JAX', name: 'Jacksonville Jaguars', conference: 'AFC', division: 'South',
    head_coach: 'Liam Coen', oc_name: 'Grant Udinski', dc_name: 'Anthony Campanile',
    off_scheme: 'McVay-tree motion + outside zone',
    off_scheme_detail: 'Coen year two: motion-heavy outside zone with Trevor Lawrence in play-action rhythm. Bhayshul Tuten seized the backfield with elite speed-to-power. Brian Thomas Jr. is the alpha; Jakobi Meyers arrived as the chain-mover. Travis Hunter’s two-way usage continues to be managed carefully.',
    def_scheme: '4-3 hybrid, sim pressures',
    def_scheme_detail: 'Josh Hines-Allen and a rebuilt secondary; Hunter’s snaps at CB are the X-factor.',
    st_coordinator: null,
    ol_analysis: 'Improved but still mid-tier; the zone scheme asks for lateral quickness over mass and mostly gets it. Tuten’s explosiveness makes average blocking look good.',
    dl_analysis: 'Hines-Allen is the constant; interior rotation is serviceable.',
    lb_analysis: 'Devin Lloyd took the leap in Campanile’s system — legit sideline-to-sideline.',
    secondary_analysis: 'Tyson Campbell + Hunter (when he plays defense) is a quality boundary pair.',
    st_analysis: 'Cam Little’s leg is a legitimate weapon (70-yarder range).',
    coach_analysis: 'Coen’s Bucs offense made everyone efficient; the same shape is emerging here. BTJ is a top-10 WR, Tuten a breakout RB1 candidate, Lawrence a value QB1. Meyers quietly soaks 90+ targets. This offense is being underdrafted as a whole.',
    primary_color: '#006778', secondary_color: '#D7A22A'
  },
  {
    abbr: 'KC', name: 'Kansas City Chiefs', conference: 'AFC', division: 'West',
    head_coach: 'Andy Reid', oc_name: 'Matt Nagy', dc_name: 'Steve Spagnuolo',
    off_scheme: 'Reid West Coast spread, layered concepts',
    off_scheme_detail: 'The empire reloaded: Kenneth Walker III arrives as reigning Super Bowl MVP to give Mahomes his best run game since prime-Kareem. Rashee Rice is the target hog underneath; Xavier Worthy stretches it. Post-Kelce, the TE room is a committee.',
    def_scheme: '4-3 blitz-heavy (Spagnuolo)',
    def_scheme_detail: 'Spags still blitzes DBs more than anyone alive. Chris Jones remains the interior terror.',
    st_coordinator: null,
    ol_analysis: 'Creed Humphrey and Trey Smith make the interior elite; tackles remain the annual soap opera. Walker’s cutback style pairs beautifully with this interior — his efficiency won’t crater from the Seattle days.',
    dl_analysis: 'Chris Jones + George Karlaftis: still top-8. Age curve is the only question.',
    lb_analysis: 'Nick Bolton is the defensive QB; excellent trigger vs. run.',
    secondary_analysis: 'Trent McDuffie is a top-5 corner playing everywhere. Spags weaponizes the slot blitz.',
    st_analysis: 'Butker steady; return units improved with speed additions.',
    coach_analysis: 'Reid’s offense with an actual RB1: Walker is a top-8 RB with TD equity attached to Mahomes drives. Rice approaches 120 targets as the underneath answer; Worthy is spike-week material. Mahomes rebounds into the top-5 QB tier.',
    primary_color: '#E31837', secondary_color: '#FFB81C'
  },
  {
    abbr: 'LV', name: 'Las Vegas Raiders', conference: 'AFC', division: 'West',
    head_coach: 'Klint Kubiak', oc_name: 'Klint Kubiak (play-caller)', dc_name: 'TBD (camp)',
    off_scheme: 'Wide zone + keepers (Kubiak/Shanahan tree)',
    off_scheme_detail: 'Rebuilt around No. 1 pick Fernando Mendoza: wide-zone with heavy play-action keepers, exactly the system that made Mendoza a Heisman winner at Indiana. Ashton Jeanty is the centerpiece; Tyler Linderbaum (record center deal) was signed to captain the line; Brock Bowers is the best TE in football and the passing game’s alpha.',
    def_scheme: '4-3 over, Crosby-centric',
    def_scheme_detail: 'The Crosby trade to Baltimore collapsed on medicals — he stays, and the defense still orbits his rush.',
    st_coordinator: null,
    ol_analysis: 'Linderbaum instantly makes the zone run game real — center is the keystone position in a Kubiak offense. Jeanty’s second-year explosion is the bet everyone in your league will be making. Believe it anyway.',
    dl_analysis: 'Crosby plays angry after the trade saga. Interior remains thin.',
    lb_analysis: 'Run-and-hit group; targeted by play-action constantly.',
    secondary_analysis: 'Young and beatable — shootout risk lives here, which helps Raiders fantasy stacks.',
    st_analysis: 'Daniel Carlson is quietly a top-10 kicker every year.',
    coach_analysis: 'Kubiak’s system is the best possible landing spot for Mendoza: defined reads, keeper game, a real center. Jeanty is a top-5 pick. Bowers might lead the league in TE targets again. Mendoza is a late-round QB with rushing juice and a friendly script.',
    primary_color: '#000000', secondary_color: '#A5ACAF'
  },
  {
    abbr: 'LAC', name: 'Los Angeles Chargers', conference: 'AFC', division: 'West',
    head_coach: 'Jim Harbaugh', oc_name: 'Greg Roman', dc_name: 'TBD (Minter to BAL)',
    off_scheme: 'Gap/power run-first, play-action shots',
    off_scheme_detail: 'Harbaugh football: multiple TEs, gap runs, and Justin Herbert throwing off play-action. Omarion Hampton is the featured hammer; Ladd McConkey is the option-route surgeon who leads the team in targets.',
    def_scheme: '3-4 disguise (post-Minter rebuild)',
    def_scheme_detail: 'Losing Minter to Baltimore hurts; Derwin James remains the scheme’s Swiss-army centerpiece.',
    st_coordinator: null,
    ol_analysis: 'Joe Alt + Rashawn Slater is the best tackle pairing in football. Power run game travels; Hampton’s goal-line role is untouchable.',
    dl_analysis: 'Tuli Tuipulotu leads a solid, unspectacular rush.',
    lb_analysis: 'Daiyan Henley broke out — top-10 coverage LB.',
    secondary_analysis: 'Derwin James still does everything. Corner depth is the worry.',
    st_analysis: 'Cameron Dicker: elite accuracy, strong fantasy option.',
    coach_analysis: 'Harbaugh compresses games: fewer possessions, more rushing TDs. Hampton is a top-10 RB on volume + goal line; McConkey a PPR top-15; Herbert an efficient-but-capped QB1 fringe. Quentin Johnston’s deep role makes him a boom-bust FLEX.',
    primary_color: '#0080C6', secondary_color: '#FFC20E'
  },
  {
    abbr: 'LAR', name: 'Los Angeles Rams', conference: 'NFC', division: 'West',
    head_coach: 'Sean McVay', oc_name: 'promoted in-house (2026)', dc_name: 'Chris Shula',
    off_scheme: 'McVay 11-personnel, condensed splits',
    off_scheme_detail: 'Stafford back on a loaded roster — the NFC favorite. Puka Nacua is the target monster; Davante Adams the red-zone technician; Kyren Williams the metronome. Ty Simpson (No. 13) waits as the succession plan.',
    def_scheme: '4-3 young speed (Shula)',
    def_scheme_detail: 'Jared Verse leads the league’s best young front seven. Ascending unit.',
    st_coordinator: null,
    ol_analysis: 'Steadily rebuilt into a top-half unit; interior chemistry is the strength. Kyren’s no-fumble, pass-pro-elite profile keeps him on the field every snap that matters.',
    dl_analysis: 'Verse + Fiske + Turner: drafted-and-developed dominance. Top-5 front by December.',
    lb_analysis: 'Fast, cheap, effective — the McVay special.',
    secondary_analysis: 'Quentin Lake organizes it; corners are competent, not stars.',
    st_analysis: 'Karty is fine; return game is an afterthought in this offense.',
    coach_analysis: 'McVay + healthy Stafford = Puka as the WR1-overall alternative to Chase. Adams soaks red-zone TDs. Kyren is a top-12 RB on trust alone. The only bear case is Stafford’s health — which makes Simpson the most interesting handcuff-QB in fantasy.',
    primary_color: '#003594', secondary_color: '#FFA300'
  },
  {
    abbr: 'MIA', name: 'Miami Dolphins', conference: 'AFC', division: 'East',
    head_coach: 'Jeff Hafley', oc_name: 'TBD (camp)', dc_name: 'Jeff Hafley (defense-first HC)',
    off_scheme: 'Zone run, QB movement (rebuild year)',
    off_scheme_detail: 'Teardown complete: Tua released (Atlanta), Waddle traded (Denver), Hill gone. Malik Willis gets the keys with a movement-based, run-leaning offense. De’Von Achane is the entire fantasy story — elite receiving back who no longer shares.',
    def_scheme: '4-3 vision-zone (Hafley system)',
    def_scheme_detail: 'Hafley’s Green Bay defense was top-5: vision-and-break zone, takeaway-hunting. Minkah Fitzpatrick returned home in the 2025 Ramsey swap.',
    st_coordinator: null,
    ol_analysis: 'Patrick Paul anchors the blind side of a rebuilding unit. Run-blocking outpaces pass-pro, which suits Willis’ escape-hatch style and Achane’s home-run angles.',
    dl_analysis: 'Bradley Chubb leads a respectable, aging rush.',
    lb_analysis: 'Jordyn Brooks tackles everything; solid mid-tier group.',
    secondary_analysis: 'Minkah is the coverage-eraser Hafley’s scheme demands. Corners are young.',
    st_analysis: 'Jason Sanders steady; return game features speed but no volume.',
    coach_analysis: 'A defense-first program in year one of a rebuild. Fantasy-wise it’s an Achane monopoly: 22+ touches weekly with screen-game gravity. Everything else is a dart throw until the QB answer arrives — treat Willis as a rushing-floor streamer only.',
    primary_color: '#008E97', secondary_color: '#FC4C02'
  },
  {
    abbr: 'MIN', name: 'Minnesota Vikings', conference: 'NFC', division: 'North',
    head_coach: 'Kevin O’Connell', oc_name: 'Wes Phillips', dc_name: 'Brian Flores',
    off_scheme: 'McVay-tree dropback + shot plays',
    off_scheme_detail: 'J.J. McCarthy’s offense now, with Kyler Murray signed (league-minimum, no-tag) as the veteran insurance/spark. Justin Jefferson remains the best route-runner alive; Aaron Jones and Jordan Mason split the backfield.',
    def_scheme: 'Flores chaos: sim pressures, zero looks',
    def_scheme_detail: 'Flores blitzes more than anyone and disguises everything. Elite vs. bad QBs, gambles vs. great ones.',
    st_coordinator: null,
    ol_analysis: 'Christian Darrisaw’s return stabilizes the blind side; interior rebuilt with vets. Protects the QB investment adequately — not a top unit, not a liability.',
    dl_analysis: 'Jonathan Greenard wins with effort and bend; Flores manufactures the rest.',
    lb_analysis: 'Blitz-weapon room by design — Pace and company attack downhill.',
    secondary_analysis: 'Byron Murphy holds up in man behind the chaos. Volatile, opportunistic unit.',
    st_analysis: 'Will Reichard is accurate with a big leg.',
    coach_analysis: 'O’Connell is a QB whisperer and Jefferson makes any QB right. JJ is a top-3 pick regardless of who throws. The Kyler subplot is the NFC’s best camp story — if he wins the job, his rushing floor makes him a QB1 value at a bench price.',
    primary_color: '#4F2683', secondary_color: '#FFC62F'
  },
  {
    abbr: 'NE', name: 'New England Patriots', conference: 'AFC', division: 'East',
    head_coach: 'Mike Vrabel', oc_name: 'Josh McDaniels', dc_name: 'Terrell Williams',
    off_scheme: 'Erhardt-Perkins, matchup-driven',
    off_scheme_detail: 'Drake Maye’s ascension got a blockbuster boost: A.J. Brown traded in from Philly to be the true alpha, with Romeo Doubs as the Z. TreVeyon Henderson and Rhamondre Stevenson split a productive backfield. McDaniels’ system finally has talent everywhere.',
    def_scheme: 'Vrabel multiple 3-4, situational',
    def_scheme_detail: 'Milton Williams was a monster signing; Christian Gonzalez is a top-5 corner. Sound, physical, top-10 unit.',
    st_coordinator: null,
    ol_analysis: 'Will Campbell settled in at LT and the interior got meaner. From league-worst to league-average in 18 months — the single biggest reason Maye’s sack rate normalized.',
    dl_analysis: 'Milton Williams wrecks interiors; Keion White flashes outside.',
    lb_analysis: 'Vrabel’s fingerprints: downhill, physical, smart.',
    secondary_analysis: 'Gonzalez shadows and wins. Safety play is steady.',
    st_analysis: 'Young kicker situation bears watching in camp.',
    coach_analysis: 'AJB changes everything: Maye jumps into the QB1 conversation (top-8 ceiling), Brown returns to top-10 WR status with a 28% target share, Henderson’s pass-game role makes him the RB2 with upside. New England is this year’s "buy the whole offense" team.',
    primary_color: '#002244', secondary_color: '#C60C30'
  },
  {
    abbr: 'NO', name: 'New Orleans Saints', conference: 'NFC', division: 'South',
    head_coach: 'Kellen Moore', oc_name: 'Doug Nussmeier', dc_name: 'Brandon Staley',
    off_scheme: 'Spread-out pace, RB screens (Moore)',
    off_scheme_detail: 'Tyler Shough won the job in 2025 and keeps it. Travis Etienne signed to headline the backfield; Chris Olave is the precise separator; rookie Jordyn Tyson was the draft’s best route-runner. Sneaky-fun offense building.',
    def_scheme: '3-4 two-high (Staley)',
    def_scheme_detail: 'Staley’s light-box math with veteran communication. Middle-tier talent, well-organized.',
    st_coordinator: null,
    ol_analysis: 'Young tackles improving; interior is the strength. Etienne’s outside-zone burst fits Moore’s stretch-and-screen tendencies well.',
    dl_analysis: 'Carl Granderson is criminally underrated; rotation lacks depth.',
    lb_analysis: 'Demario Davis, ageless, still the brain of the operation.',
    secondary_analysis: 'Kool-Aid McKinstry emerged as a true CB1. Safety depth thin.',
    st_analysis: 'Grupe accurate inside 50; return game middling.',
    coach_analysis: 'Moore’s offenses scheme easy completions and RB targets — Etienne’s receiving revival is the fantasy angle (RB2 with RB1 weeks). Olave is a WR2 with 110-target certainty; Tyson is the rookie WR to stash. Shough is deep-league only.',
    primary_color: '#D3BC8D', secondary_color: '#101820'
  },
  {
    abbr: 'NYG', name: 'New York Giants', conference: 'NFC', division: 'East',
    head_coach: 'John Harbaugh', oc_name: 'TBD (camp)', dc_name: 'TBD (camp)',
    off_scheme: 'Balanced pro-style, situational mastery',
    off_scheme_detail: 'The stunner of the cycle: John Harbaugh to the Giants. Jaxson Dart gets the league’s best program-builder. Cam Skattebo’s contact balance made him a cult hero; Malik Nabers is a top-5 WR talent entering his prime. Structure arrives.',
    def_scheme: '3-4 pressure (Harbaugh DNA)',
    def_scheme_detail: 'Dexter Lawrence, Brian Burns, and Abdul Carter is the scariest front in the NFC — Harbaugh inherits a ready-made defense.',
    st_coordinator: null,
    ol_analysis: 'Improving young five — still the roster’s weakest link, but Harbaugh’s programs fix OL play first. Skattebo’s yards-after-contact style masks blocking lapses.',
    dl_analysis: 'Lawrence is a top-2 nose; Burns + Carter bring 25 combined sacks of upside.',
    lb_analysis: 'Bobby Okereke steadies a fast group.',
    secondary_analysis: 'Young corners will be schemed help. The front covers for them.',
    st_analysis: 'Harbaugh special teams are always top-5 — hidden yardage incoming.',
    coach_analysis: 'Harbaugh’s track record with young QBs (Flacco, Lamar) makes Dart the development story of the year. Nabers is a top-8 WR with target-monopoly upside (30% share in reach). Skattebo’s volume is safe; efficiency depends on the line’s growth.',
    primary_color: '#0B2265', secondary_color: '#A71930'
  },
  {
    abbr: 'NYJ', name: 'New York Jets', conference: 'AFC', division: 'East',
    head_coach: 'Aaron Glenn', oc_name: 'Tanner Engstrand', dc_name: 'Steve Wilks',
    off_scheme: 'Run-heavy, motion West Coast',
    off_scheme_detail: 'Justin Fields’ dual-threat profile drives a run-first attack. Breece Hall’s contract-year usage and Garrett Wilson’s target monopoly are the fantasy pillars. Rookie EDGE David Bailey (No. 2 overall) headlines the other side.',
    def_scheme: '4-3 aggressive man (Glenn DNA)',
    def_scheme_detail: 'Post-Sauce (traded to IND in 2025): Bailey + Will McDonald rush while young corners battle in man.',
    st_coordinator: null,
    ol_analysis: 'Olu Fashanu is a top-12 LT now; the interior invests in the run game. Designed-QB-run pulls give this line easy angles — Fields’ rushing floor is scheme-protected.',
    dl_analysis: 'Bailey’s first-step is special. This front will be a problem by midseason.',
    lb_analysis: 'Quincy Williams plays like his hair is on fire. Fun, occasionally reckless.',
    secondary_analysis: 'Rebuilt and young — growing pains guaranteed, garbage-time passing production for opponents likely.',
    st_analysis: 'Average unit overall.',
    coach_analysis: 'Glenn builds bullies. Fields is a top-8 fantasy QB on rushing volume alone; Wilson’s 28% target share in a low-volume passing game nets WR2 numbers; Hall is the classic contract-year volume bet. Mason Taylor is a sneaky TE2 with red-zone growth.',
    primary_color: '#125740', secondary_color: '#000000'
  },
  {
    abbr: 'PHI', name: 'Philadelphia Eagles', conference: 'NFC', division: 'East',
    head_coach: 'Nick Sirianni', oc_name: 'Kevin Patullo', dc_name: 'Vic Fangio',
    off_scheme: 'RPO + gap power, tush-push empire',
    off_scheme_detail: 'Post-AJB trade (to New England): DeVonta Smith ascends to alpha, rookie Makai Lemon slots in day one, and the offense re-centers on Saquon Barkley and Hurts’ legs. Less volume drama, more run dominance.',
    def_scheme: 'Fangio two-high, rush four',
    def_scheme_detail: 'Fangio’s master-class shell with Jalen Carter commanding doubles. Still a top-5 defense.',
    st_coordinator: null,
    ol_analysis: 'The best OL in football, again — Lane Johnson and a ruthless interior. Saquon’s lanes are chef-crafted; the tush push remains automatic, which caps everyone’s TD math except Hurts’.',
    dl_analysis: 'Carter is the best interior player in the NFC. Wave rush behind him.',
    lb_analysis: 'Zack Baun’s All-Pro leap held. Elite second level.',
    secondary_analysis: 'Quinyon Mitchell is a rising star CB1; Cooper DeJean owns the slot.',
    st_analysis: 'Jake Elliott reliable from distance.',
    coach_analysis: 'The AJB trade clarifies everything: Smith becomes a 120-target WR1, Saquon stays a top-3 pick behind this line, Hurts remains fantasy’s best TD cheat code. Lemon’s draft capital says instant WR3-with-upside. Goedert’s red-zone role grows.',
    primary_color: '#004C54', secondary_color: '#A5ACAF'
  },
  {
    abbr: 'PIT', name: 'Pittsburgh Steelers', conference: 'AFC', division: 'North',
    head_coach: 'Mike McCarthy', oc_name: 'Mike McCarthy (play-caller)', dc_name: 'Teryl Austin',
    off_scheme: 'West Coast timing, boundary iso shots',
    off_scheme_detail: 'The Tomlin era ended; McCarthy inherits Aaron Rodgers (one more year) with DK Metcalf and Michael Pittman Jr. (free-agent add) outside. Jaylen Warren and Rico Dowdle form a committee. Veteran ceiling, veteran fragility.',
    def_scheme: '3-4 zone-blitz heritage',
    def_scheme_detail: 'T.J. Watt still wrecks games; Austin keeps the Steelers structure intact.',
    st_coordinator: null,
    ol_analysis: 'Young line matured together — Broderick Jones settled down. Pass-pro is average, which is a real concern for a 43-year-old QB’s time-to-throw.',
    dl_analysis: 'Watt + Highsmith remains a top edge duo; Keeanu Benton anchors.',
    lb_analysis: 'Patrick Queen runs the show; strong tackling unit.',
    secondary_analysis: 'Joey Porter Jr. is a physical boundary presence; slot is targetable.',
    st_analysis: 'Boswell is a top-5 kicker, automatic in wind.',
    coach_analysis: 'McCarthy’s West Coast rhythm suits Rodgers’ quick release. Metcalf is the WR2 with WR1 weeks; Pittman the possession WR3 in PPR. The backfield split kills ceiling for both RBs — Warren the preferred side. Rodgers is a bridge QB2 in fantasy terms.',
    primary_color: '#FFB612', secondary_color: '#101820'
  },
  {
    abbr: 'SF', name: 'San Francisco 49ers', conference: 'NFC', division: 'West',
    head_coach: 'Kyle Shanahan', oc_name: 'Klay Kubiak', dc_name: 'Robert Saleh’s successor (TBD)',
    off_scheme: 'The Shanahan system, YAC-maximal',
    off_scheme_detail: 'Mike Evans (one-year, ring-chasing) joins CMC, Kittle, Pearsall, and Jennings. Purdy operates the league’s most schemed offense. Saleh left for Tennessee’s HC job; the defense re-tools again.',
    def_scheme: '4-3 wide-9, zone-heavy',
    def_scheme_detail: 'Bosa headlines; the back seven is younger and cheaper than the dynasty years.',
    st_coordinator: null,
    ol_analysis: 'Trent Williams’ age is the annual storyline; the interior is scheme-carried. Outside zone still functions at an elite level because Shanahan’s angles do the blocking.',
    dl_analysis: 'Bosa remains a top-5 edge. Depth thinner than the championship window years.',
    lb_analysis: 'Fred Warner is still the best LB alive. Full stop.',
    secondary_analysis: 'Lenoir leads a young, competent group that the scheme protects.',
    st_analysis: 'Kicker competition worth monitoring in camp.',
    coach_analysis: 'CMC’s workload management is the only question — when active he’s a top-5 RB. Evans’ red-zone mastery + Purdy’s accuracy = double-digit TD upside at a WR3 price. Kittle remains a top-5 TE. Pearsall’s ascent is real but crowded.',
    primary_color: '#AA0000', secondary_color: '#B3995D'
  },
  {
    abbr: 'SEA', name: 'Seattle Seahawks', conference: 'NFC', division: 'West',
    head_coach: 'Mike Macdonald', oc_name: 'Klint Kubiak’s successor (TBD)', dc_name: 'Aden Durde',
    off_scheme: 'Zone run + play-action (post-Kubiak)',
    off_scheme_detail: 'Kenneth Walker left for KC; Zach Charbonnet and explosive rookie Jadarian Price split the backfield. Jaxon Smith-Njigba is coming off a target-share explosion — the offense flows through him. Darnold’s stability holds.',
    def_scheme: 'Macdonald multiple, disguise-heavy',
    def_scheme_detail: 'The Ravens-style pressure system matured: Witherspoon blitzes from the slot, safeties rotate late. Top-8 unit.',
    st_coordinator: null,
    ol_analysis: 'Young interior finally jelled late in 2025. Zone-scheme fits favor Charbonnet’s patience over Price’s burst early — watch the camp split closely.',
    dl_analysis: 'Leonard Williams remains a wrecking ball inside.',
    lb_analysis: 'Ernest Jones tackles everything between the numbers.',
    secondary_analysis: 'Witherspoon + Julian Love: versatile, violent, opportunistic.',
    st_analysis: 'Jason Myers has a big, weather-tested leg.',
    coach_analysis: 'JSN is a top-5 WR — the volume is locked and Macdonald’s defense keeps games close (positive script). The backfield is the fantasy riddle: Charbonnet opens as the starter but Price’s juice wins by October. Darnold is a matchup QB2.',
    primary_color: '#002244', secondary_color: '#69BE28'
  },
  {
    abbr: 'TB', name: 'Tampa Bay Buccaneers', conference: 'NFC', division: 'South',
    head_coach: 'Todd Bowles', oc_name: 'Josh Grizzard', dc_name: 'Todd Bowles (play-caller)',
    off_scheme: 'Spread with duo run game',
    off_scheme_detail: 'Post-Evans (49ers): Emeka Egbuka is the new WR1 after a stellar rookie year, Chris Godwin the veteran slot. Bucky Irving is a top-10 RB coming off a breakout. Baker keeps the magic going.',
    def_scheme: '3-4 blitz-heavy (Bowles)',
    def_scheme_detail: 'Bowles still sends zero pressure more than anyone in the NFC. Vita Vea anchors.',
    st_coordinator: null,
    ol_analysis: 'Tristan Wirfs is a top-3 tackle; interior solid. Irving’s vision behind duo blocking produced elite broken-tackle numbers — sustainable.',
    dl_analysis: 'Vea + Calijah Kancey: interior disruption is the identity.',
    lb_analysis: 'Post-David era rebuild at ILB — the defense’s soft spot.',
    secondary_analysis: 'Winfield Jr. is a top-3 safety when healthy; corners run hot and cold.',
    st_analysis: 'Chase McLaughlin quietly excellent.',
    coach_analysis: 'Egbuka steps into the Evans target vacuum — 26% share is realistic, making him a top-15 WR bet. Irving is a locked top-10 RB. Baker remains a borderline QB1 who wins you weeks in shootouts. Godwin’s PPR floor persists in the slot.',
    primary_color: '#D50A0A', secondary_color: '#34302B'
  },
  {
    abbr: 'TEN', name: 'Tennessee Titans', conference: 'AFC', division: 'South',
    head_coach: 'Robert Saleh', oc_name: 'TBD (camp)', dc_name: 'Robert Saleh (defense-first HC)',
    off_scheme: 'Wide zone + bootleg (Shanahan-tree OC)',
    off_scheme_detail: 'Cam Ward year two with real weapons: No. 4 pick Carnell Tate outside, Wan’Dale Robinson in the slot, Tony Pollard steady. The offense modernizes around Ward’s creativity.',
    def_scheme: '4-3 wide-9 (Saleh system)',
    def_scheme_detail: 'Saleh’s simple-and-fast structure with Jeffery Simmons finally in an attack role. L’Jarius Sneed bounce-back year.',
    st_coordinator: null,
    ol_analysis: 'Rebuilt through consecutive drafts — JC Latham anchors. Still bottom-third but trending up; Ward’s mobility papers over protection cracks.',
    dl_analysis: 'Simmons is a top-5 interior force in an attacking scheme at last.',
    lb_analysis: 'Young and fast, Saleh’s type. Growing pains vs. play-action.',
    secondary_analysis: 'Sneed healthy is a shadow corner; safety depth remains thin.',
    st_analysis: 'Average across the board.',
    coach_analysis: 'Saleh brings the program structure Tennessee has lacked. Tate’s polish makes him the rookie WR1 in fantasy (immediate 20% share); Wan’Dale is a PPR-only floor piece; Pollard grinds out RB2 value. Ward is a late-round QB with rushing-plus-arm-talent upside.',
    primary_color: '#0C2340', secondary_color: '#4B92DB'
  },
  {
    abbr: 'WAS', name: 'Washington Commanders', conference: 'NFC', division: 'East',
    head_coach: 'Dan Quinn', oc_name: 'Kliff Kingsbury', dc_name: 'Joe Whitt Jr.',
    off_scheme: 'Air raid-influenced spread (Kingsbury)',
    off_scheme_detail: 'Jayden Daniels’ offense: spread sets, RPO layers, designed keepers. Terry McLaurin remains the trusted alpha; Deebo Samuel’s hybrid role continues; the backfield is a committee with Croskey-Merritt leading.',
    def_scheme: '4-3 pressure-sim (Quinn/Whitt)',
    def_scheme_detail: 'Quinn’s energy with Whitt’s coverage detail. Lattimore’s health dictates the ceiling.',
    st_coordinator: null,
    ol_analysis: 'Laremy Tunsil stabilized the blind side; interior improved to average. Daniels’ escape ability turns average protection into explosive plays — the line just has to not lose immediately.',
    dl_analysis: 'Daron Payne leads a solid interior; edge rush is committee-based.',
    lb_analysis: 'Frankie Luvu is a blitzing menace — one of the league’s most fun defenders.',
    secondary_analysis: 'Quan Martin emerged; Lattimore’s availability is the swing factor.',
    st_analysis: 'Solid; Daniels’ kneel-slides have ended several return opportunities (joke — unit is fine).',
    coach_analysis: 'Daniels is a top-3 fantasy QB — rushing floor plus year-three passing leap. McLaurin is the 110-target WR1; Deebo a touch-based FLEX; the RB room is a fantasy headache to avoid outside deep leagues. Stack Daniels + McLaurin where possible.',
    primary_color: '#5A1414', secondary_color: '#FFB612'
  }
];
