import { useApi } from '../../api';

/**
 * What the model is actually looking at, across every decision it has made.
 *
 * The blind replay returns a verdict — 157 bets, -10.43% ROI — and a verdict
 * without a reason cannot be acted on. This is the reason: each decision's basis
 * reconstructed from the twenty-two component predictions that produced it, then
 * compiled so the model's habits become visible rather than its record.
 *
 * The explanations are generated by template from the same numbers, not by
 * asking a language model what it thinks it did. That makes them free,
 * reproducible, and guaranteed consistent with the aggregate below them.
 */

interface Component {
  id: string; name: string; family: string;
  decisions_led: number; record: string; win_rate: number | null;
  units: number | null; mean_deviation_from_market: number | null;
  z_vs_break_even: number | null; significant: boolean | null;
}
interface Compiled {
  decisions: number; overall_record: string; overall_win_rate: number | null;
  units: number | null; break_even_at_minus_110: number;
  decision_shape: { concentrated: number; diffuse: number; mixed: number; note: string };
  multiple_comparisons: { components_tested: number; sidak_corrected_alpha: number;
    z_required: number; note: string };
  what_the_model_leans_on: Component[];
  components_significantly_losing: Component[];
  components_significantly_winning: Component[];
  suggestive_but_not_significant: { name: string; record: string; win_rate: number; z: number }[];
  verdict: string; note: string; error?: string;
}
interface Detail {
  season: number; week: number; matchup: string; side: string;
  market_margin: number; model_margin: number; edge: number;
  result: string; units: number | null; narrative: string;
  drivers: { name: string; deviation_from_market: number; weight: number;
    contribution: number; agreed_with_bet: boolean }[];
}

const pct = (v: number | null | undefined) =>
  v == null ? '—' : `${(v * 100).toFixed(1)}%`;

export default function Decisions() {
  const { data, loading } = useApi<Compiled>('/betting/decisions');
  const { data: detail } = useApi<Detail[]>('/betting/decisions/detail');

  // Gate on data as well as the flag. The underlying race was fixed in useApi,
  // but a page should still render the moment it has something to show rather
  // than waiting on a boolean.
  if (!data && loading) {
    return <div className="card p-6 text-sm text-slate-500">Compiling decision bases…</div>;
  }
  if (!data || data.error) {
    return (
      <div className="card p-6">
        <h2 className="font-semibold text-slate-900">No decision bases recorded</h2>
        <p className="mt-1 text-sm text-slate-600">{data?.error ?? 'Nothing to compile yet.'}</p>
      </div>
    );
  }

  const profitable = (data.overall_win_rate ?? 0) > data.break_even_at_minus_110;

  return (
    <div className="space-y-4">
      <div className="card p-4">
        <h2 className="font-semibold text-slate-900">What the model is looking at</h2>
        <p className="mt-1 text-sm text-slate-600">
          Every decision's basis, reconstructed from the component predictions that produced it. The
          explanations below are rendered by template from those same numbers — deterministic, free,
          and reproducible, rather than a language model's account of its own reasoning.
        </p>
      </div>

      <div className="grid gap-3 sm:grid-cols-4">
        <Stat label="Decisions compiled" value={String(data.decisions)} />
        <Stat label="Record" value={data.overall_record} />
        <Stat label="Win rate" value={pct(data.overall_win_rate)}
          sub={`need ${pct(data.break_even_at_minus_110)}`} tone={profitable ? 'good' : 'bad'} />
        <Stat label="Units" value={String(data.units ?? '—')}
          tone={(data.units ?? 0) > 0 ? 'good' : 'bad'} />
      </div>

      <div className="card p-4">
        <h3 className="text-sm font-semibold text-slate-900">Shape of the decisions</h3>
        <div className="mt-3 grid gap-3 sm:grid-cols-3">
          <Stat label="Diffuse" value={String(data.decision_shape.diffuse)}
            sub="no component above 20%" />
          <Stat label="Mixed" value={String(data.decision_shape.mixed)} />
          <Stat label="Concentrated" value={String(data.decision_shape.concentrated)}
            sub="one component above 40%" />
        </div>
        <p className="mt-2 text-xs text-slate-500">{data.decision_shape.note}</p>
      </div>

      <div className="card p-4">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h3 className="text-sm font-semibold text-slate-900">What leads each decision</h3>
          <span className="font-mono text-xs text-slate-400">
            |z| &gt; {data.multiple_comparisons.z_required} required
          </span>
        </div>
        <p className="mt-1 text-xs text-slate-500">{data.multiple_comparisons.note}</p>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="text-xs uppercase tracking-wide text-slate-400">
              <tr>
                <th className="py-1 text-left">Component</th>
                <th className="text-right">Led</th><th className="text-right">Record</th>
                <th className="text-right">Win rate</th><th className="text-right">Units</th>
                <th className="text-right">z</th><th className="text-right">Verdict</th>
              </tr>
            </thead>
            <tbody>
              {data.what_the_model_leans_on.map(c => (
                <tr key={c.id} className="border-t border-slate-100">
                  <td className="py-1.5 text-slate-700">{c.name}</td>
                  <td className="text-right tabular-nums text-slate-600">{c.decisions_led}</td>
                  <td className="text-right tabular-nums text-slate-600">{c.record}</td>
                  <td className={`text-right tabular-nums ${
                    (c.win_rate ?? 0) > 0.5238 ? 'text-emerald-700' : 'text-slate-900'}`}>
                    {pct(c.win_rate)}</td>
                  <td className={`text-right tabular-nums ${
                    (c.units ?? 0) > 0 ? 'text-emerald-700' : 'text-rose-700'}`}>{c.units}</td>
                  <td className="text-right tabular-nums text-slate-500">{c.z_vs_break_even}</td>
                  <td className="text-right text-xs">
                    {c.significant
                      ? <span className="font-medium text-sky-700">significant</span>
                      : <span className="text-slate-400">noise</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className={`card p-4 ${data.components_significantly_losing.length
        ? 'border-amber-200 bg-amber-50/50' : ''}`}>
        <h3 className="text-sm font-semibold text-slate-900">Verdict</h3>
        <p className="mt-2 text-sm text-slate-800">{data.verdict}</p>
        {data.suggestive_but_not_significant.length > 0 && (
          <p className="mt-2 text-xs text-slate-500">
            Suggestive but not significant:{' '}
            {data.suggestive_but_not_significant.map(s => `${s.name} (${s.record})`).join(', ')}.
            These are the rates that would look like findings without correcting for having examined
            every component.
          </p>
        )}
      </div>

      {Array.isArray(detail) && detail.length > 0 && (
        <div className="card p-4">
          <h3 className="text-sm font-semibold text-slate-900">Individual decisions</h3>
          <p className="mt-1 text-xs text-slate-500">
            Each explanation is template-rendered from the decision's own numbers. No tokens spent.
          </p>
          <div className="mt-3 space-y-3">
            {detail.slice(0, 12).map((d, i) => (
              <div key={i} className="border-t border-slate-100 pt-3">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <span className="text-sm font-medium text-slate-900">
                    {d.season} wk{d.week} · {d.matchup}
                  </span>
                  <span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase ${
                    d.result === 'Won' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>
                    {d.result}
                  </span>
                </div>
                <p className="mt-1 text-sm leading-relaxed text-slate-700">{d.narrative}</p>
                {d.drivers?.length > 0 && (
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {d.drivers.slice(0, 5).map((dr, j) => (
                      <span key={j} className={`rounded px-1.5 py-0.5 font-mono text-[10px] ${
                        dr.agreed_with_bet ? 'bg-sky-50 text-sky-700' : 'bg-slate-100 text-slate-500'}`}>
                        {dr.name} {dr.deviation_from_market > 0 ? '+' : ''}{dr.deviation_from_market}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function Stat({ label, value, sub, tone }: {
  label: string; value: string; sub?: string; tone?: 'good' | 'bad';
}) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-3">
      <div className="text-xs uppercase tracking-wide text-slate-400">{label}</div>
      <div className={`mt-1 text-xl font-semibold tabular-nums ${
        tone === 'good' ? 'text-emerald-700' : tone === 'bad' ? 'text-rose-700' : 'text-slate-900'}`}>
        {value}
      </div>
      {sub && <div className="mt-0.5 text-xs text-slate-500">{sub}</div>}
    </div>
  );
}
